# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flight.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66light.proto\"\x07\n\x05\x45mpty\"\x1b\n\rFlightRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"Q\n\x0e\x46lightResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x0e\n\x06prices\x18\x03 \x01(\x05\x12\x0e\n\x06places\x18\x04 \x01(\x05\".\n\nFlightList\x12 \n\x07\x66lights\x18\x01 \x03(\x0b\x32\x0f.FlightResponse2`\n\rFlightService\x12!\n\nGetFlights\x12\x06.Empty\x1a\x0b.FlightList\x12,\n\tGetFlight\x12\x0e.FlightRequest\x1a\x0f.FlightResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=16
  _globals['_EMPTY']._serialized_end=23
  _globals['_FLIGHTREQUEST']._serialized_start=25
  _globals['_FLIGHTREQUEST']._serialized_end=52
  _globals['_FLIGHTRESPONSE']._serialized_start=54
  _globals['_FLIGHTRESPONSE']._serialized_end=135
  _globals['_FLIGHTLIST']._serialized_start=137
  _globals['_FLIGHTLIST']._serialized_end=183
  _globals['_FLIGHTSERVICE']._serialized_start=185
  _globals['_FLIGHTSERVICE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
